apiVersion: apps/v1
kind: Deployment
metadata:
  name: torch-cpu-anshumand
  namespace: digits
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: torch-cpu-anshumand
  template:
    metadata:
      labels:
        k8s-app: torch-cpu-anshumand
    spec:
      tolerations:
      - key: "region"
        operator: "Equal"
        value: "allow"
        effect: "NoSchedule"
      containers:
      - name: torch-cpu-anshumand
        image: gitlab-registry.nrp-nautilus.io/anshumand/pytorch-lightning-smoke-detection:latest
        # Define the port you want to run jupyter lab on. If not defined, will default to 8888.
        env:
        - name: MY_JUPYTER_LAB_PORT
          value: "8888"
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        # command: ["/bin/sh", "-c"]
        # args: ["sleep infinity"]
        resources:
          limits:
            memory: "64Gi"
            cpu: "8"
          requests:
            memory: "16Gi"
            cpu: "2"
        volumeMounts:
        - mountPath: /userdata/kerasData
          name: modeltraining
      volumes:
        - name: modeltraining
          persistentVolumeClaim:
            claimName: modeltraining
